### ISSUE TITLE
Docker Compose Example

### ISSUE THREAD

**Issue by BadCo-NZ** [machengim/oasis#26]
It would help users to include a docker compose example

Here is mine:

```
version: '3.3'

services:
  oasis:
    container_name: oasis
    image: machengim/oasis
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - '/mnt/docker-data/oasis-data:/opt/oasis/data'
```

If you would like I could do a PR.

Thanks,
BadCo.
